# Generated by Django 3.0.6 on 2020-06-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_cat_count'),
        ('subCategory', '0002_auto_20200601_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Cat'),
        ),
    ]
