# Generated by Django 3.0.6 on 2020-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subCategory', '0003_auto_20200602_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
