# Generated by Django 3.0.6 on 2020-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200524_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
