# Generated by Django 3.0.6 on 2020-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
