# Generated by Django 3.0.6 on 2020-05-29 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200528_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_created=datetime.date, auto_now_add=True),
        ),
    ]
