# Generated by Django 3.0.6 on 2020-05-29 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200529_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_created=datetime.datetime(2020, 5, 29, 10, 49, 26, 42774)),
        ),
    ]
