# Generated by Django 3.0.6 on 2020-05-29 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200529_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 8, 4, 11, 737783, tzinfo=utc)),
        ),
    ]
