# Generated by Django 3.0.6 on 2020-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200529_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='00:00', max_length=12),
        ),
    ]
