# Generated by Django 3.0.6 on 2020-05-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200529_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='00:00', max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
