# Generated by Django 3.0.6 on 2020-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200529_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
