# Generated by Django 3.0.6 on 2020-05-31 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200529_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
