# Generated by Django 3.0.6 on 2020-06-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200601_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='time',
        ),
    ]
