# Generated by Django 3.0.6 on 2020-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='oCatId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
