# Generated by Django 3.0.6 on 2020-06-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_cat_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='count',
        ),
    ]
