# Generated by Django 3.0.6 on 2020-06-04 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_auto_20200603_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
