# Generated by Django 3.0.6 on 2020-06-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_contactform_newsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='newsId',
        ),
    ]
