# Generated by Django 3.0.6 on 2020-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0005_remove_contactform_newsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('txt', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
                ('newsId', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
