# Generated by Django 3.0.6 on 2020-06-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0006_commentsform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentsForm',
            new_name='Comments',
        ),
    ]
