# Generated by Django 3.0.6 on 2020-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200523_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.TextField(default='https://www.facebook.com/behrang.shams'),
        ),
        migrations.AddField(
            model_name='main',
            name='instagram',
            field=models.TextField(default='https://www.instagram.com/behrang_shams/'),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.TextField(default='https://twitter.com/'),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(default='this site designed by berkan sems just for learning django '),
        ),
    ]
