# Generated by Django 3.0.6 on 2020-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200523_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/behrang.shams', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/behrang_shams/', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='https://twitter.com/', max_length=50),
        ),
    ]
