# Generated by Django 3.0.6 on 2020-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub',
            new_name='Book',
        ),
    ]
